# enable mouse
set -g mouse on

# correct terminal type for truecolor Neovim inside tmux
set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

# status bar style
set -g status-style "bg=#333333 fg=#5eacd3"

# Set prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# start windows at 1, not 0
set -g base-index 1

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
